package heroes.journey.modlib

object IdsC {
    // --- DEMON ---
    // Render IDs
    const val RENDER_CLAWED_ABOMINATION = "render_clawed_abomination"
    const val RENDER_ANTLERED_RASCAL = "render_antlered_rascal"
    const val RENDER_CRIMSON_IMP = "render_crimson_imp"
    const val RENDER_DEPRAVED_BLACKGUARD = "render_depraved_blackguard"
    const val RENDER_FLEDGLING_DEMON = "render_fledgling_demon"
    const val RENDER_FLOATING_EYE = "render_floating_eye"
    const val RENDER_FOUL_GOUGER = "render_foul_gouger"
    const val RENDER_GRINNING_GREMLIN = "render_grinning_gremlin"
    const val RENDER_NEFARIOUS_SCAMP = "render_nefarious_scamp"
    const val RENDER_PIT_BALOR = "render_pit_balor"
    const val RENDER_POINTED_DEMONSPAWN = "render_pointed_demonspawn"
    const val RENDER_RASCALLY_DEMONLING = "render_rascally_demonling"
    const val RENDER_SKEWERING_STALKER = "render_skewering_stalker"
    const val RENDER_TAINTED_SCOUNDREL = "render_tainted_scoundrel"
    const val RENDER_WARP_SKULL = "render_warp_skull"
    // Challenge IDs
    const val CHALLENGE_CLAWED_ABOMINATION = "clawed_abomination"
    const val CHALLENGE_ANTLERED_RASCAL = "antlered_rascal"
    const val CHALLENGE_CRIMSON_IMP = "crimson_imp"
    const val CHALLENGE_DEPRAVED_BLACKGUARD = "depraved_blackguard"
    const val CHALLENGE_FLEDGLING_DEMON = "fledgling_demon"
    const val CHALLENGE_FLOATING_EYE = "floating_eye"
    const val CHALLENGE_FOUL_GOUGER = "foul_gouger"
    const val CHALLENGE_GRINNING_GREMLIN = "grinning_gremlin"
    const val CHALLENGE_NEFARIOUS_SCAMP = "nefarious_scamp"
    const val CHALLENGE_PIT_BALOR = "pit_balor"
    const val CHALLENGE_POINTED_DEMONSPAWN = "pointed_demonspawn"
    const val CHALLENGE_RASCALLY_DEMONLING = "rascally_demonling"
    const val CHALLENGE_SKEWERING_STALKER = "skewering_stalker"
    const val CHALLENGE_TAINTED_SCOUNDREL = "tainted_scoundrel"
    const val CHALLENGE_WARP_SKULL = "warp_skull"

    // --- DRAGON ---
    // Render IDs
    const val RENDER_ADULT_GREEN_DRAGON = "render_adult_green_dragon"
    const val RENDER_ADULT_WHITE_DRAGON = "render_adult_white_dragon"
    const val RENDER_AQUA_DRAKE = "render_aqua_drake"
    const val RENDER_BABY_BRASS_DRAGON = "render_baby_brass_dragon"
    const val RENDER_BABY_COPPER_DRAGON = "render_baby_copper_dragon"
    const val RENDER_BABY_GREEN_DRAGON = "render_baby_green_dragon"
    const val RENDER_BABY_WHITE_DRAGON = "render_baby_white_dragon"
    const val RENDER_JUVENILE_BRONZE_DRAGON = "render_juvenile_bronze_dragon"
    const val RENDER_MATURE_BRONZE_DRAGON = "render_mature_bronze_dragon"
    const val RENDER_MUD_WYVERN = "render_mud_wyvern"
    const val RENDER_POISON_DRAKE = "render_poison_drake"
    const val RENDER_PYGMY_WYVERN = "render_pygmy_wyvern"
    const val RENDER_VIRIDIAN_DRAKE = "render_viridian_drake"
    const val RENDER_YOUNG_BRASS_DRAGON = "render_young_brass_dragon"
    const val RENDER_YOUNG_RED_DRAGON = "render_young_red_dragon"
    // Challenge IDs
    const val CHALLENGE_ADULT_GREEN_DRAGON = "adult_green_dragon"
    const val CHALLENGE_ADULT_WHITE_DRAGON = "adult_white_dragon"
    const val CHALLENGE_AQUA_DRAKE = "aqua_drake"
    const val CHALLENGE_BABY_BRASS_DRAGON = "baby_brass_dragon"
    const val CHALLENGE_BABY_COPPER_DRAGON = "baby_copper_dragon"
    const val CHALLENGE_BABY_GREEN_DRAGON = "baby_green_dragon"
    const val CHALLENGE_BABY_WHITE_DRAGON = "baby_white_dragon"
    const val CHALLENGE_JUVENILE_BRONZE_DRAGON = "juvenile_bronze_dragon"
    const val CHALLENGE_MATURE_BRONZE_DRAGON = "mature_bronze_dragon"
    const val CHALLENGE_MUD_WYVERN = "mud_wyvern"
    const val CHALLENGE_POISON_DRAKE = "poison_drake"
    const val CHALLENGE_PYGMY_WYVERN = "pygmy_wyvern"
    const val CHALLENGE_VIRIDIAN_DRAKE = "viridian_drake"
    const val CHALLENGE_YOUNG_BRASS_DRAGON = "young_brass_dragon"
    const val CHALLENGE_YOUNG_RED_DRAGON = "young_red_dragon"

    // --- HOLY ---
    // Render IDs
    const val RENDER_BLESSED_GLADIATOR = "render_blessed_gladiator"
    const val RENDER_BOLD_MAN_AT_ARMS = "render_bold_man_at_arms"
    const val RENDER_DETERMINED_SOLDIER = "render_determined_soldier"
    const val RENDER_DEVOUT_ACOLYTE = "render_devout_acolyte"
    const val RENDER_DIVINE_PLANETAR = "render_divine_planetar"
    const val RENDER_FAVORED_CLERIC = "render_favored_cleric"
    const val RENDER_FLOATING_CHERUB = "render_floating_cherub"
    const val RENDER_GENTLE_SHEPARD = "render_gentle_shepard"
    const val RENDER_HOLY_CRUSADER = "render_holy_crusader"
    const val RENDER_JOVIAL_FRIAR = "render_jovial_friar"
    const val RENDER_RESOLUTE_ANGEL = "render_resolute_angel"
    const val RENDER_RIGHTEOUS_DEVA = "render_righteous_deva"
    const val RENDER_SWORD_ARCHON = "render_sword_archon"
    const val RENDER_VETERAN_SWORDSMAN = "render_veteran_swordsman"
    const val RENDER_ZEALOUS_PRIEST = "render_zealous_priest"
    // Challenge IDs
    const val CHALLENGE_BLESSED_GLADIATOR = "blessed_gladiator"
    const val CHALLENGE_BOLD_MAN_AT_ARMS = "bold_man_at_arms"
    const val CHALLENGE_DETERMINED_SOLDIER = "determined_soldier"
    const val CHALLENGE_DEVOUT_ACOLYTE = "devout_acolyte"
    const val CHALLENGE_DIVINE_PLANETAR = "divine_planetar"
    const val CHALLENGE_FAVORED_CLERIC = "favored_cleric"
    const val CHALLENGE_FLOATING_CHERUB = "floating_cherub"
    const val CHALLENGE_GENTLE_SHEPARD = "gentle_shepard"
    const val CHALLENGE_HOLY_CRUSADER = "holy_crusader"
    const val CHALLENGE_JOVIAL_FRIAR = "jovial_friar"
    const val CHALLENGE_RESOLUTE_ANGEL = "resolute_angel"
    const val CHALLENGE_RIGHTEOUS_DEVA = "righteous_deva"
    const val CHALLENGE_SWORD_ARCHON = "sword_archon"
    const val CHALLENGE_VETERAN_SWORDSMAN = "veteran_swordsman"
    const val CHALLENGE_ZEALOUS_PRIEST = "zealous_priest"

    // --- HUMANOID ---
    // Render IDs
    const val RENDER_BESTIAL_LIZARDFOLK = "render_bestial_lizardfolk"
    const val RENDER_GOBLIN_ARCHER = "render_goblin_archer"
    const val RENDER_GOBLIN_FANATIC = "render_goblin_fanatic"
    const val RENDER_GOBLIN_FIGHTER = "render_goblin_fighter"
    const val RENDER_GOBLIN_OCCULTIST = "render_goblin_occultist"
    const val RENDER_GOBLIN_WOLF_RIDER = "render_goblin_wolf_rider"
    const val RENDER_HALFLING_ASSASSIN = "render_halfling_assassin"
    const val RENDER_HALFLING_BARD = "render_halfling_bard"
    const val RENDER_HALFLING_RANGER = "render_halfling_ranger"
    const val RENDER_HALFLING_ROGUE = "render_halfling_rogue"
    const val RENDER_HALFLING_SLINGER = "render_halfling_slinger"
    const val RENDER_LIZARDFOLK_ARCHER = "render_lizardfolk_archer"
    const val RENDER_LIZARDFOLK_GLADIATOR = "render_lizardfolk_gladiator"
    const val RENDER_LIZARDFOLK_SCOUT = "render_lizardfolk_scout"
    const val RENDER_LIZARDFOLK_SPEARMAN = "render_lizardfolk_spearman"
    // Challenge IDs
    const val CHALLENGE_BESTIAL_LIZARDFOLK = "bestial_lizardfolk"
    const val CHALLENGE_GOBLIN_ARCHER = "goblin_archer"
    const val CHALLENGE_GOBLIN_FANATIC = "goblin_fanatic"
    const val CHALLENGE_GOBLIN_FIGHTER = "goblin_fighter"
    const val CHALLENGE_GOBLIN_OCCULTIST = "goblin_occultist"
    const val CHALLENGE_GOBLIN_WOLF_RIDER = "goblin_wolf_rider"
    const val CHALLENGE_HALFLING_ASSASSIN = "halfling_assassin"
    const val CHALLENGE_HALFLING_BARD = "halfling_bard"
    const val CHALLENGE_HALFLING_RANGER = "halfling_ranger"
    const val CHALLENGE_HALFLING_ROGUE = "halfling_rogue"
    const val CHALLENGE_HALFLING_SLINGER = "halfling_slinger"
    const val CHALLENGE_LIZARDFOLK_ARCHER = "lizardfolk_archer"
    const val CHALLENGE_LIZARDFOLK_GLADIATOR = "lizardfolk_gladiator"
    const val CHALLENGE_LIZARDFOLK_SCOUT = "lizardfolk_scout"
    const val CHALLENGE_LIZARDFOLK_SPEARMAN = "lizardfolk_spearman"

    // --- HUMANOID II ---
    // Render IDs
    const val RENDER_ADVENTUROUS_ADOLESCENT = "render_adventurous_adolescent"
    const val RENDER_BOISTEROUS_YOUTH = "render_boisterous_youth"
    const val RENDER_ELF_BLADEDANCER = "render_elf_bladedancer"
    const val RENDER_ELF_ENCHANTER = "render_elf_enchanter"
    const val RENDER_ELF_LORD = "render_elf_lord"
    const val RENDER_ELF_SHARPSHOOTER = "render_elf_sharpshooter"
    const val RENDER_ELF_WAYFARER = "render_elf_wayfarer"
    const val RENDER_JOYFUL_KID = "render_joyful_kid"
    const val RENDER_MERFOLK_AQUAMANCER = "render_merfolk_aquamancer"
    const val RENDER_MERFOLK_IMPALER = "render_merfolk_impaler"
    const val RENDER_MERFOLK_JAVELINEER = "render_merfolk_javelineer"
    const val RENDER_MERFOLK_MYSTIC = "render_merfolk_mystic"
    const val RENDER_MERFOLK_SCOUT = "render_merfolk_scout"
    const val RENDER_OVERWORKED_VILLAGER = "render_overworked_villager"
    const val RENDER_PLAYFUL_CHILD = "render_playful_child"
    // Challenge IDs
    const val CHALLENGE_ADVENTUROUS_ADOLESCENT = "adventurous_adolescent"
    const val CHALLENGE_BOISTEROUS_YOUTH = "boisterous_youth"
    const val CHALLENGE_ELF_BLADEDANCER = "elf_bladedancer"
    const val CHALLENGE_ELF_ENCHANTER = "elf_enchanter"
    const val CHALLENGE_ELF_LORD = "elf_lord"
    const val CHALLENGE_ELF_SHARPSHOOTER = "elf_sharpshooter"
    const val CHALLENGE_ELF_WAYFARER = "elf_wayfarer"
    const val CHALLENGE_JOYFUL_KID = "joyful_kid"
    const val CHALLENGE_MERFOLK_AQUAMANCER = "merfolk_aquamancer"
    const val CHALLENGE_MERFOLK_IMPALER = "merfolk_impaler"
    const val CHALLENGE_MERFOLK_JAVELINEER = "merfolk_javelineer"
    const val CHALLENGE_MERFOLK_MYSTIC = "merfolk_mystic"
    const val CHALLENGE_MERFOLK_SCOUT = "merfolk_scout"
    const val CHALLENGE_OVERWORKED_VILLAGER = "overworked_villager"
    const val CHALLENGE_PLAYFUL_CHILD = "playful_child"

    // --- MAGICAL ---
    // Render IDs
    const val RENDER_MAGICAL_FAIRY = "render_magical_fairy"
    const val RENDER_ADEPT_NECROMANCER = "render_adept_necromancer"
    const val RENDER_CORRUPTED_TREANT = "render_corrupted_treant"
    const val RENDER_DEFT_SORCERESS = "render_deft_sorceress"
    const val RENDER_EARTH_ELEMENTAL = "render_earth_elemental"
    const val RENDER_EXPERT_DRUID = "render_expert_druid"
    const val RENDER_FIRE_ELEMENTAL = "render_fire_elemental"
    const val RENDER_FLUTTERING_PIXIE = "render_fluttering_pixie"
    const val RENDER_GLOWING_WISP = "render_glowing_wisp"
    const val RENDER_GRIZZLED_TREANT = "render_grizzled_treant"
    const val RENDER_ICE_GOLEM = "render_ice_golem"
    const val RENDER_IRON_GOLEM = "render_iron_golem"
    const val RENDER_NOVICE_PYROMANCER = "render_novice_pyromancer"
    const val RENDER_VILE_WITCH = "render_vile_witch"
    const val RENDER_WATER_ELEMENTAL = "render_water_elemental"
    // Challenge IDs
    const val CHALLENGE_MAGICAL_FAIRY = "magical_fairy"
    const val CHALLENGE_ADEPT_NECROMANCER = "adept_necromancer"
    const val CHALLENGE_CORRUPTED_TREANT = "corrupted_treant"
    const val CHALLENGE_DEFT_SORCERESS = "deft_sorceress"
    const val CHALLENGE_EARTH_ELEMENTAL = "earth_elemental"
    const val CHALLENGE_EXPERT_DRUID = "expert_druid"
    const val CHALLENGE_FIRE_ELEMENTAL = "fire_elemental"
    const val CHALLENGE_FLUTTERING_PIXIE = "fluttering_pixie"
    const val CHALLENGE_GLOWING_WISP = "glowing_wisp"
    const val CHALLENGE_GRIZZLED_TREANT = "grizzled_treant"
    const val CHALLENGE_ICE_GOLEM = "ice_golem"
    const val CHALLENGE_IRON_GOLEM = "iron_golem"
    const val CHALLENGE_NOVICE_PYROMANCER = "novice_pyromancer"
    const val CHALLENGE_VILE_WITCH = "vile_witch"
    const val CHALLENGE_WATER_ELEMENTAL = "water_elemental"

    // --- MONSTER ---
    // Render IDs
    const val RENDER_BLINDED_GRIMLOCK = "render_blinded_grimlock"
    const val RENDER_BLOODSHOT_EYE = "render_bloodshot_eye"
    const val RENDER_BRAWNY_OGRE = "render_brawny_ogre"
    const val RENDER_CRIMSON_SLAAD = "render_crimson_slaad"
    const val RENDER_CRUSHING_CYCLOPS = "render_crushing_cyclops"
    const val RENDER_DEATH_SLIME = "render_death_slime"
    const val RENDER_FUNGAL_MYCONID = "render_fungal_myconid"
    const val RENDER_HUMONGOUS_ETTIN = "render_humongous_ettin"
    const val RENDER_MURKY_SLAAD = "render_murky_slaad"
    const val RENDER_OCHRE_JELLY = "render_ochre_jelly"
    const val RENDER_OCULAR_WATCHER = "render_ocular_watcher"
    const val RENDER_RED_CAP = "render_red_cap"
    const val RENDER_SHRIEKER_MUSHROOM = "render_shrieker_mushroom"
    const val RENDER_STONE_TROLL = "render_stone_troll"
    const val RENDER_SWAMP_TROLL = "render_swamp_troll"
    // Challenge IDs
    const val CHALLENGE_BLINDED_GRIMLOCK = "blinded_grimlock"
    const val CHALLENGE_BLOODSHOT_EYE = "bloodshot_eye"
    const val CHALLENGE_BRAWNY_OGRE = "brawny_ogre"
    const val CHALLENGE_CRIMSON_SLAAD = "crimson_slaad"
    const val CHALLENGE_CRUSHING_CYCLOPS = "crushing_cyclops"
    const val CHALLENGE_DEATH_SLIME = "death_slime"
    const val CHALLENGE_FUNGAL_MYCONID = "fungal_myconid"
    const val CHALLENGE_HUMONGOUS_ETTIN = "humongous_ettin"
    const val CHALLENGE_MURKY_SLAAD = "murky_slaad"
    const val CHALLENGE_OCHRE_JELLY = "ochre_jelly"
    const val CHALLENGE_OCULAR_WATCHER = "ocular_watcher"
    const val CHALLENGE_RED_CAP = "red_cap"
    const val CHALLENGE_SHRIEKER_MUSHROOM = "shrieker_mushroom"
    const val CHALLENGE_STONE_TROLL = "stone_troll"
    const val CHALLENGE_SWAMP_TROLL = "swamp_troll"

    // --- UNDEAD ---
    // Render IDs
    const val RENDER_BOUND_CADAVER = "render_bound_cadaver"
    const val RENDER_BRITTLE_ARCHER = "render_brittle_archer"
    const val RENDER_CARCASS_FEEDER = "render_carcass_feeder"
    const val RENDER_DECREPIT_BONES = "render_decrepit_bones"
    const val RENDER_DISMEMBERED_CRAWLER = "render_dismembered_crawler"
    const val RENDER_GHASTLY_EYE = "render_ghastly_eye"
    const val RENDER_GIANT_ROYAL_SCARAB = "render_giant_royal_scarab"
    const val RENDER_GRAVE_REVENANT = "render_grave_revenant"
    const val RENDER_MUTILATED_STUMBLER = "render_mutilated_stumbler"
    const val RENDER_ROYAL_SCARAB = "render_royal_scarab"
    const val RENDER_SAND_GHOUL = "render_sand_ghoul"
    const val RENDER_SKITTERING_HAND = "render_skittering_hand"
    const val RENDER_TOXIC_HOUND = "render_toxic_hound"
    const val RENDER_UNRAVELING_CRAWLER = "render_unraveling_crawler"
    const val RENDER_VAMPIRE_BAT = "render_vampire_bat"
    // Challenge IDs
    const val CHALLENGE_BOUND_CADAVER = "bound_cadaver"
    const val CHALLENGE_BRITTLE_ARCHER = "brittle_archer"
    const val CHALLENGE_CARCASS_FEEDER = "carcass_feeder"
    const val CHALLENGE_DECREPIT_BONES = "decrepit_bones"
    const val CHALLENGE_DISMEMBERED_CRAWLER = "dismembered_crawler"
    const val CHALLENGE_GHASTLY_EYE = "ghastly_eye"
    const val CHALLENGE_GIANT_ROYAL_SCARAB = "giant_royal_scarab"
    const val CHALLENGE_GRAVE_REVENANT = "grave_revenant"
    const val CHALLENGE_MUTILATED_STUMBLER = "mutilated_stumbler"
    const val CHALLENGE_ROYAL_SCARAB = "royal_scarab"
    const val CHALLENGE_SAND_GHOUL = "sand_ghoul"
    const val CHALLENGE_SKITTERING_HAND = "skittering_hand"
    const val CHALLENGE_TOXIC_HOUND = "toxic_hound"
    const val CHALLENGE_UNRAVELING_CRAWLER = "unraveling_crawler"
    const val CHALLENGE_VAMPIRE_BAT = "vampire_bat"

    // --- VERMIN ---
    // Render IDs
    const val RENDER_ACID_ANT = "render_acid_ant"
    const val RENDER_BLOATED_BEDBUG = "render_bloated_bedbug"
    const val RENDER_DUNG_BEETLE = "render_dung_beetle"
    const val RENDER_ENGORGED_TICK = "render_engorged_tick"
    const val RENDER_FAMISHED_TICK = "render_famished_tick"
    const val RENDER_FORAGING_MAGGOT = "render_foraging_maggot"
    const val RENDER_INFECTED_MOUSE = "render_infected_mouse"
    const val RENDER_LAVA_ANT = "render_lava_ant"
    const val RENDER_MAWING_BEAVER = "render_mawing_beaver"
    const val RENDER_PLAGUE_BAT = "render_plague_bat"
    const val RENDER_RHINO_BEETLE = "render_rhino_beetle"
    const val RENDER_SOLDIER_ANT = "render_soldier_ant"
    const val RENDER_SWOOPING_BAT = "render_swooping_bat"
    const val RENDER_TAINTED_COCKROACH = "render_tainted_cockroach"
    const val RENDER_TUNNELING_MOLE = "render_tunneling_mole"
    // Challenge IDs
    const val CHALLENGE_ACID_ANT = "acid_ant"
    const val CHALLENGE_BLOATED_BEDBUG = "bloated_bedbug"
    const val CHALLENGE_DUNG_BEETLE = "dung_beetle"
    const val CHALLENGE_ENGORGED_TICK = "engorged_tick"
    const val CHALLENGE_FAMISHED_TICK = "famished_tick"
    const val CHALLENGE_FORAGING_MAGGOT = "foraging_maggot"
    const val CHALLENGE_INFECTED_MOUSE = "infected_mouse"
    const val CHALLENGE_LAVA_ANT = "lava_ant"
    const val CHALLENGE_MAWING_BEAVER = "mawing_beaver"
    const val CHALLENGE_PLAGUE_BAT = "plague_bat"
    const val CHALLENGE_RHINO_BEETLE = "rhino_beetle"
    const val CHALLENGE_SOLDIER_ANT = "soldier_ant"
    const val CHALLENGE_SWOOPING_BAT = "swooping_bat"
    const val CHALLENGE_TAINTED_COCKROACH = "tainted_cockroach"
    const val CHALLENGE_TUNNELING_MOLE = "tunneling_mole"
} 